version: "3.9"
services:
    psqlDb:
        image: postgres:11.12
        ports: 
            - "5432:5432"
        environment: 
            POSTGRES_USER: sustainablegardenuser
            POSTGRES_PASSWORD: password
            POSTGRES_DB: sustainablegarden

    backend:
        build: .
        command: >
            bash -c "python manage.py migrate
            && python manage.py createsuperuser --noinput
            && python manage.py runserver 0.0.0.0:8000"
        ports: 
            - "8000:8000"
        depends_on: 
            - psqlDb
        environment:
             DJANGO_SUPERUSER_USERNAME: admin
             DJANGO_SUPERUSER_PASSWORD: adminPassword
             DJANGO_SUPERUSER_EMAIL: admin@admin123.com